CREATE TABLE IF NOT EXISTS `leaderboard` (
	`Name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Score` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Rank` INT(10) UNSIGNED NULL DEFAULT NULL,
	`Year` INT(10) UNSIGNED NULL DEFAULT NULL,
	`Month` INT(10) UNSIGNED NULL DEFAULT NULL,
	UNIQUE INDEX `Rank` (`Rank`) USING BTREE,
	UNIQUE INDEX `Name` (`Name`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE IF NOT EXISTS `users` (
	`Username` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Email` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Password` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ID` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
	UNIQUE INDEX `Username` (`Username`) USING BTREE,
	UNIQUE INDEX `Email` (`Email`) USING BTREE,
	UNIQUE INDEX `ID` (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;